//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Senac.Fecomercio.WebApi.svcBaixaChamado {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gtec.cielo.com.br/BaixaChamado/v1", ConfigurationName="svcBaixaChamado.BaixaChamadoSoap")]
    public interface BaixaChamadoSoap {
        
        // CODEGEN: O parâmetro 'filtroChamados' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://gtec.cielo.com.br/BaixaChamado/v1/BaixarChamado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Senac.Fecomercio.WebApi.svcBaixaChamado.BaixarChamadoResponse BaixarChamado(Senac.Fecomercio.WebApi.svcBaixaChamado.BaixarChamadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gtec.cielo.com.br/BaixaChamado/v1/BaixarChamado", ReplyAction="*")]
        System.Threading.Tasks.Task<Senac.Fecomercio.WebApi.svcBaixaChamado.BaixarChamadoResponse> BaixarChamadoAsync(Senac.Fecomercio.WebApi.svcBaixaChamado.BaixarChamadoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gtec.cielo.com.br/BaixaChamado/v1")]
    public partial class WSFiltroChamadoBaixa : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int numeroChamadoField;
        
        private bool numeroChamadoFieldSpecified;
        
        private int numeroChamadoEdsField;
        
        private bool numeroChamadoEdsFieldSpecified;
        
        private int sequencialField;
        
        private bool sequencialFieldSpecified;
        
        private int numeroLogicoField;
        
        private bool numeroLogicoFieldSpecified;
        
        private WSInstalacaoRetirada instalacaoRetiradaField;
        
        private bool instalacaoRetiradaFieldSpecified;
        
        private long estabelecimentoField;
        
        private bool estabelecimentoFieldSpecified;
        
        private string tipoSolucaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int numeroChamado {
            get {
                return this.numeroChamadoField;
            }
            set {
                this.numeroChamadoField = value;
                this.RaisePropertyChanged("numeroChamado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroChamadoSpecified {
            get {
                return this.numeroChamadoFieldSpecified;
            }
            set {
                this.numeroChamadoFieldSpecified = value;
                this.RaisePropertyChanged("numeroChamadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int numeroChamadoEds {
            get {
                return this.numeroChamadoEdsField;
            }
            set {
                this.numeroChamadoEdsField = value;
                this.RaisePropertyChanged("numeroChamadoEds");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroChamadoEdsSpecified {
            get {
                return this.numeroChamadoEdsFieldSpecified;
            }
            set {
                this.numeroChamadoEdsFieldSpecified = value;
                this.RaisePropertyChanged("numeroChamadoEdsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int sequencial {
            get {
                return this.sequencialField;
            }
            set {
                this.sequencialField = value;
                this.RaisePropertyChanged("sequencial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sequencialSpecified {
            get {
                return this.sequencialFieldSpecified;
            }
            set {
                this.sequencialFieldSpecified = value;
                this.RaisePropertyChanged("sequencialSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int numeroLogico {
            get {
                return this.numeroLogicoField;
            }
            set {
                this.numeroLogicoField = value;
                this.RaisePropertyChanged("numeroLogico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroLogicoSpecified {
            get {
                return this.numeroLogicoFieldSpecified;
            }
            set {
                this.numeroLogicoFieldSpecified = value;
                this.RaisePropertyChanged("numeroLogicoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public WSInstalacaoRetirada instalacaoRetirada {
            get {
                return this.instalacaoRetiradaField;
            }
            set {
                this.instalacaoRetiradaField = value;
                this.RaisePropertyChanged("instalacaoRetirada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool instalacaoRetiradaSpecified {
            get {
                return this.instalacaoRetiradaFieldSpecified;
            }
            set {
                this.instalacaoRetiradaFieldSpecified = value;
                this.RaisePropertyChanged("instalacaoRetiradaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long estabelecimento {
            get {
                return this.estabelecimentoField;
            }
            set {
                this.estabelecimentoField = value;
                this.RaisePropertyChanged("estabelecimento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estabelecimentoSpecified {
            get {
                return this.estabelecimentoFieldSpecified;
            }
            set {
                this.estabelecimentoFieldSpecified = value;
                this.RaisePropertyChanged("estabelecimentoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string tipoSolucao {
            get {
                return this.tipoSolucaoField;
            }
            set {
                this.tipoSolucaoField = value;
                this.RaisePropertyChanged("tipoSolucao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gtec.cielo.com.br/BaixaChamado/v1")]
    public enum WSInstalacaoRetirada {
        
        /// <remarks/>
        Instalacao,
        
        /// <remarks/>
        Retirada,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gtec.cielo.com.br/BaixaChamado/v1")]
    public partial class WSContraOrdem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int chamadoField;
        
        private int sequencialField;
        
        private int contraOrdemNumeroField;
        
        private bool contraOrdemNumeroFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int chamado {
            get {
                return this.chamadoField;
            }
            set {
                this.chamadoField = value;
                this.RaisePropertyChanged("chamado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int sequencial {
            get {
                return this.sequencialField;
            }
            set {
                this.sequencialField = value;
                this.RaisePropertyChanged("sequencial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int contraOrdemNumero {
            get {
                return this.contraOrdemNumeroField;
            }
            set {
                this.contraOrdemNumeroField = value;
                this.RaisePropertyChanged("contraOrdemNumero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool contraOrdemNumeroSpecified {
            get {
                return this.contraOrdemNumeroFieldSpecified;
            }
            set {
                this.contraOrdemNumeroFieldSpecified = value;
                this.RaisePropertyChanged("contraOrdemNumeroSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gtec.cielo.com.br/BaixaChamado/v1")]
    public partial class WSRespostaBaixa : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoField;
        
        private string mensagemField;
        
        private WSContraOrdem[] listaContraOrdemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
                this.RaisePropertyChanged("mensagem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public WSContraOrdem[] listaContraOrdem {
            get {
                return this.listaContraOrdemField;
            }
            set {
                this.listaContraOrdemField = value;
                this.RaisePropertyChanged("listaContraOrdem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaixarChamado", WrapperNamespace="http://gtec.cielo.com.br/BaixaChamado/v1", IsWrapped=true)]
    public partial class BaixarChamadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gtec.cielo.com.br/BaixaChamado/v1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filtroChamados")]
        public Senac.Fecomercio.WebApi.svcBaixaChamado.WSFiltroChamadoBaixa[] filtroChamados;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gtec.cielo.com.br/BaixaChamado/v1", Order=1)]
        public System.DateTime contraOrdemHora;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gtec.cielo.com.br/BaixaChamado/v1", Order=2)]
        public string contraOrdemContatoEc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gtec.cielo.com.br/BaixaChamado/v1", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gtec.cielo.com.br/BaixaChamado/v1", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dominio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gtec.cielo.com.br/BaixaChamado/v1", Order=5)]
        public string cpfTecnico;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gtec.cielo.com.br/BaixaChamado/v1", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string servicoExecutado;
        
        public BaixarChamadoRequest() {
        }
        
        public BaixarChamadoRequest(Senac.Fecomercio.WebApi.svcBaixaChamado.WSFiltroChamadoBaixa[] filtroChamados, System.DateTime contraOrdemHora, string contraOrdemContatoEc, string usuario, string dominio, string cpfTecnico, string servicoExecutado) {
            this.filtroChamados = filtroChamados;
            this.contraOrdemHora = contraOrdemHora;
            this.contraOrdemContatoEc = contraOrdemContatoEc;
            this.usuario = usuario;
            this.dominio = dominio;
            this.cpfTecnico = cpfTecnico;
            this.servicoExecutado = servicoExecutado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaixarChamadoResponse", WrapperNamespace="http://gtec.cielo.com.br/BaixaChamado/v1", IsWrapped=true)]
    public partial class BaixarChamadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gtec.cielo.com.br/BaixaChamado/v1", Order=0)]
        public Senac.Fecomercio.WebApi.svcBaixaChamado.WSRespostaBaixa BaixarChamadoResult;
        
        public BaixarChamadoResponse() {
        }
        
        public BaixarChamadoResponse(Senac.Fecomercio.WebApi.svcBaixaChamado.WSRespostaBaixa BaixarChamadoResult) {
            this.BaixarChamadoResult = BaixarChamadoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BaixaChamadoSoapChannel : Senac.Fecomercio.WebApi.svcBaixaChamado.BaixaChamadoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BaixaChamadoSoapClient : System.ServiceModel.ClientBase<Senac.Fecomercio.WebApi.svcBaixaChamado.BaixaChamadoSoap>, Senac.Fecomercio.WebApi.svcBaixaChamado.BaixaChamadoSoap {
        
        public BaixaChamadoSoapClient() {
        }
        
        public BaixaChamadoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BaixaChamadoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BaixaChamadoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BaixaChamadoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Senac.Fecomercio.WebApi.svcBaixaChamado.BaixarChamadoResponse Senac.Fecomercio.WebApi.svcBaixaChamado.BaixaChamadoSoap.BaixarChamado(Senac.Fecomercio.WebApi.svcBaixaChamado.BaixarChamadoRequest request) {
            return base.Channel.BaixarChamado(request);
        }
        
        public Senac.Fecomercio.WebApi.svcBaixaChamado.WSRespostaBaixa BaixarChamado(Senac.Fecomercio.WebApi.svcBaixaChamado.WSFiltroChamadoBaixa[] filtroChamados, System.DateTime contraOrdemHora, string contraOrdemContatoEc, string usuario, string dominio, string cpfTecnico, string servicoExecutado) {
            Senac.Fecomercio.WebApi.svcBaixaChamado.BaixarChamadoRequest inValue = new Senac.Fecomercio.WebApi.svcBaixaChamado.BaixarChamadoRequest();
            inValue.filtroChamados = filtroChamados;
            inValue.contraOrdemHora = contraOrdemHora;
            inValue.contraOrdemContatoEc = contraOrdemContatoEc;
            inValue.usuario = usuario;
            inValue.dominio = dominio;
            inValue.cpfTecnico = cpfTecnico;
            inValue.servicoExecutado = servicoExecutado;
            Senac.Fecomercio.WebApi.svcBaixaChamado.BaixarChamadoResponse retVal = ((Senac.Fecomercio.WebApi.svcBaixaChamado.BaixaChamadoSoap)(this)).BaixarChamado(inValue);
            return retVal.BaixarChamadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Senac.Fecomercio.WebApi.svcBaixaChamado.BaixarChamadoResponse> Senac.Fecomercio.WebApi.svcBaixaChamado.BaixaChamadoSoap.BaixarChamadoAsync(Senac.Fecomercio.WebApi.svcBaixaChamado.BaixarChamadoRequest request) {
            return base.Channel.BaixarChamadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Senac.Fecomercio.WebApi.svcBaixaChamado.BaixarChamadoResponse> BaixarChamadoAsync(Senac.Fecomercio.WebApi.svcBaixaChamado.WSFiltroChamadoBaixa[] filtroChamados, System.DateTime contraOrdemHora, string contraOrdemContatoEc, string usuario, string dominio, string cpfTecnico, string servicoExecutado) {
            Senac.Fecomercio.WebApi.svcBaixaChamado.BaixarChamadoRequest inValue = new Senac.Fecomercio.WebApi.svcBaixaChamado.BaixarChamadoRequest();
            inValue.filtroChamados = filtroChamados;
            inValue.contraOrdemHora = contraOrdemHora;
            inValue.contraOrdemContatoEc = contraOrdemContatoEc;
            inValue.usuario = usuario;
            inValue.dominio = dominio;
            inValue.cpfTecnico = cpfTecnico;
            inValue.servicoExecutado = servicoExecutado;
            return ((Senac.Fecomercio.WebApi.svcBaixaChamado.BaixaChamadoSoap)(this)).BaixarChamadoAsync(inValue);
        }
    }
}
