//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/comum/v1")]
    public partial class Fault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string descricaoField;
        
        private Tipo tipoField;
        
        private string sistemaOrigemField;
        
        private string servicoOrigemField;
        
        private FaultDetail[] detalheField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
                this.RaisePropertyChanged("descricao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Tipo tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string sistemaOrigem {
            get {
                return this.sistemaOrigemField;
            }
            set {
                this.sistemaOrigemField = value;
                this.RaisePropertyChanged("sistemaOrigem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string servicoOrigem {
            get {
                return this.servicoOrigemField;
            }
            set {
                this.servicoOrigemField = value;
                this.RaisePropertyChanged("servicoOrigem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("detalhe", Order=5)]
        public FaultDetail[] detalhe {
            get {
                return this.detalheField;
            }
            set {
                this.detalheField = value;
                this.RaisePropertyChanged("detalhe");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/comum/v1")]
    public enum Tipo {
        
        /// <remarks/>
        NEGOCIO,
        
        /// <remarks/>
        TECNICO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/comum/v1")]
    public partial class FaultDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.cielo.com.br/operacao/logistica/equipamento/v9/consultarterminalde" +
        "talhado")]
    public partial class DadosProcessamentoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> codigoRetornoField;
        
        private bool codigoRetornoFieldSpecified;
        
        private string descricaoMensagemRetornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> codigoRetorno {
            get {
                return this.codigoRetornoField;
            }
            set {
                this.codigoRetornoField = value;
                this.RaisePropertyChanged("codigoRetorno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoRetornoSpecified {
            get {
                return this.codigoRetornoFieldSpecified;
            }
            set {
                this.codigoRetornoFieldSpecified = value;
                this.RaisePropertyChanged("codigoRetornoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string descricaoMensagemRetorno {
            get {
                return this.descricaoMensagemRetornoField;
            }
            set {
                this.descricaoMensagemRetornoField = value;
                this.RaisePropertyChanged("descricaoMensagemRetorno");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.cielo.com.br/operacao/logistica/equipamento/v9/consultarterminalde" +
        "talhado")]
    public partial class DadosUltimaInicializacaoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime dataUltimaInicializacaoField;
        
        private bool dataUltimaInicializacaoFieldSpecified;
        
        private System.DateTime horaUltimaInicializacaoField;
        
        private bool horaUltimaInicializacaoFieldSpecified;
        
        private string indicadorInicializacaoField;
        
        private string numeroSerieTerminalUltimaInicializacaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime dataUltimaInicializacao {
            get {
                return this.dataUltimaInicializacaoField;
            }
            set {
                this.dataUltimaInicializacaoField = value;
                this.RaisePropertyChanged("dataUltimaInicializacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataUltimaInicializacaoSpecified {
            get {
                return this.dataUltimaInicializacaoFieldSpecified;
            }
            set {
                this.dataUltimaInicializacaoFieldSpecified = value;
                this.RaisePropertyChanged("dataUltimaInicializacaoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time", Order=1)]
        public System.DateTime horaUltimaInicializacao {
            get {
                return this.horaUltimaInicializacaoField;
            }
            set {
                this.horaUltimaInicializacaoField = value;
                this.RaisePropertyChanged("horaUltimaInicializacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool horaUltimaInicializacaoSpecified {
            get {
                return this.horaUltimaInicializacaoFieldSpecified;
            }
            set {
                this.horaUltimaInicializacaoFieldSpecified = value;
                this.RaisePropertyChanged("horaUltimaInicializacaoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string indicadorInicializacao {
            get {
                return this.indicadorInicializacaoField;
            }
            set {
                this.indicadorInicializacaoField = value;
                this.RaisePropertyChanged("indicadorInicializacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string numeroSerieTerminalUltimaInicializacao {
            get {
                return this.numeroSerieTerminalUltimaInicializacaoField;
            }
            set {
                this.numeroSerieTerminalUltimaInicializacaoField = value;
                this.RaisePropertyChanged("numeroSerieTerminalUltimaInicializacao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.cielo.com.br/operacao/logistica/equipamento/v9/consultarterminalde" +
        "talhado")]
    public partial class DadosRetornoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoRetornoMensagemField;
        
        private string descricaoRetornoMensagemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string codigoRetornoMensagem {
            get {
                return this.codigoRetornoMensagemField;
            }
            set {
                this.codigoRetornoMensagemField = value;
                this.RaisePropertyChanged("codigoRetornoMensagem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string descricaoRetornoMensagem {
            get {
                return this.descricaoRetornoMensagemField;
            }
            set {
                this.descricaoRetornoMensagemField = value;
                this.RaisePropertyChanged("descricaoRetornoMensagem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.cielo.com.br/operacao/logistica/equipamento/v9/consultarterminalde" +
        "talhado")]
    public partial class DadosGrupoSolucaoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descricaoGrupoSolucaoField;
        
        private string siglaGrupoSolucaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string descricaoGrupoSolucao {
            get {
                return this.descricaoGrupoSolucaoField;
            }
            set {
                this.descricaoGrupoSolucaoField = value;
                this.RaisePropertyChanged("descricaoGrupoSolucao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string siglaGrupoSolucao {
            get {
                return this.siglaGrupoSolucaoField;
            }
            set {
                this.siglaGrupoSolucaoField = value;
                this.RaisePropertyChanged("siglaGrupoSolucao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.cielo.com.br/operacao/logistica/equipamento/v9/consultarterminalde" +
        "talhado")]
    public partial class DadosEquipamentoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoCategoriaField;
        
        private string codigoOperadoraSIMCardField;
        
        private string codigoOperadorLogisticoField;
        
        private string codigoNoMobileField;
        
        private string codigoNoPrimarioField;
        
        private string codigoNoSecundarioField;
        
        private string codigoNoServicoField;
        
        private string codigoNoTelecargaField;
        
        private string codigoUsoTerminalField;
        
        private string codigoVersaoAplicativoField;
        
        private string descricaoCompletaField;
        
        private string descricaoModeloField;
        
        private string descricaoResumidaField;
        
        private bool indicadorBloqueioField;
        
        private bool indicadorBloqueioFieldSpecified;
        
        private bool indicadorDescontinuadoField;
        
        private bool indicadorDescontinuadoFieldSpecified;
        
        private string descricaoTerminalMarketingField;
        
        private string indicadorPareamentoPinpadField;
        
        private bool indicadorPossuiChipField;
        
        private bool indicadorPossuiChipFieldSpecified;
        
        private bool indicadorPossuiTecladoField;
        
        private bool indicadorPossuiTecladoFieldSpecified;
        
        private bool indicadorPossuiTrilhaField;
        
        private bool indicadorPossuiTrilhaFieldSpecified;
        
        private string nomeGrupoSolucaoCapturaField;
        
        private string nomeTecnologiaField;
        
        private long numeroAcessoField;
        
        private bool numeroAcessoFieldSpecified;
        
        private string numeroLogicoField;
        
        private string numeroSerieField;
        
        private string siglaTipoTerminalField;
        
        private string codigoSIMCardField;
        
        private string indicadorCanalOrigemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string codigoCategoria {
            get {
                return this.codigoCategoriaField;
            }
            set {
                this.codigoCategoriaField = value;
                this.RaisePropertyChanged("codigoCategoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string codigoOperadoraSIMCard {
            get {
                return this.codigoOperadoraSIMCardField;
            }
            set {
                this.codigoOperadoraSIMCardField = value;
                this.RaisePropertyChanged("codigoOperadoraSIMCard");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string codigoOperadorLogistico {
            get {
                return this.codigoOperadorLogisticoField;
            }
            set {
                this.codigoOperadorLogisticoField = value;
                this.RaisePropertyChanged("codigoOperadorLogistico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string codigoNoMobile {
            get {
                return this.codigoNoMobileField;
            }
            set {
                this.codigoNoMobileField = value;
                this.RaisePropertyChanged("codigoNoMobile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string codigoNoPrimario {
            get {
                return this.codigoNoPrimarioField;
            }
            set {
                this.codigoNoPrimarioField = value;
                this.RaisePropertyChanged("codigoNoPrimario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string codigoNoSecundario {
            get {
                return this.codigoNoSecundarioField;
            }
            set {
                this.codigoNoSecundarioField = value;
                this.RaisePropertyChanged("codigoNoSecundario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string codigoNoServico {
            get {
                return this.codigoNoServicoField;
            }
            set {
                this.codigoNoServicoField = value;
                this.RaisePropertyChanged("codigoNoServico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string codigoNoTelecarga {
            get {
                return this.codigoNoTelecargaField;
            }
            set {
                this.codigoNoTelecargaField = value;
                this.RaisePropertyChanged("codigoNoTelecarga");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string codigoUsoTerminal {
            get {
                return this.codigoUsoTerminalField;
            }
            set {
                this.codigoUsoTerminalField = value;
                this.RaisePropertyChanged("codigoUsoTerminal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string codigoVersaoAplicativo {
            get {
                return this.codigoVersaoAplicativoField;
            }
            set {
                this.codigoVersaoAplicativoField = value;
                this.RaisePropertyChanged("codigoVersaoAplicativo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string descricaoCompleta {
            get {
                return this.descricaoCompletaField;
            }
            set {
                this.descricaoCompletaField = value;
                this.RaisePropertyChanged("descricaoCompleta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string descricaoModelo {
            get {
                return this.descricaoModeloField;
            }
            set {
                this.descricaoModeloField = value;
                this.RaisePropertyChanged("descricaoModelo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string descricaoResumida {
            get {
                return this.descricaoResumidaField;
            }
            set {
                this.descricaoResumidaField = value;
                this.RaisePropertyChanged("descricaoResumida");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool indicadorBloqueio {
            get {
                return this.indicadorBloqueioField;
            }
            set {
                this.indicadorBloqueioField = value;
                this.RaisePropertyChanged("indicadorBloqueio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool indicadorBloqueioSpecified {
            get {
                return this.indicadorBloqueioFieldSpecified;
            }
            set {
                this.indicadorBloqueioFieldSpecified = value;
                this.RaisePropertyChanged("indicadorBloqueioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public bool indicadorDescontinuado {
            get {
                return this.indicadorDescontinuadoField;
            }
            set {
                this.indicadorDescontinuadoField = value;
                this.RaisePropertyChanged("indicadorDescontinuado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool indicadorDescontinuadoSpecified {
            get {
                return this.indicadorDescontinuadoFieldSpecified;
            }
            set {
                this.indicadorDescontinuadoFieldSpecified = value;
                this.RaisePropertyChanged("indicadorDescontinuadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string descricaoTerminalMarketing {
            get {
                return this.descricaoTerminalMarketingField;
            }
            set {
                this.descricaoTerminalMarketingField = value;
                this.RaisePropertyChanged("descricaoTerminalMarketing");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string indicadorPareamentoPinpad {
            get {
                return this.indicadorPareamentoPinpadField;
            }
            set {
                this.indicadorPareamentoPinpadField = value;
                this.RaisePropertyChanged("indicadorPareamentoPinpad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public bool indicadorPossuiChip {
            get {
                return this.indicadorPossuiChipField;
            }
            set {
                this.indicadorPossuiChipField = value;
                this.RaisePropertyChanged("indicadorPossuiChip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool indicadorPossuiChipSpecified {
            get {
                return this.indicadorPossuiChipFieldSpecified;
            }
            set {
                this.indicadorPossuiChipFieldSpecified = value;
                this.RaisePropertyChanged("indicadorPossuiChipSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public bool indicadorPossuiTeclado {
            get {
                return this.indicadorPossuiTecladoField;
            }
            set {
                this.indicadorPossuiTecladoField = value;
                this.RaisePropertyChanged("indicadorPossuiTeclado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool indicadorPossuiTecladoSpecified {
            get {
                return this.indicadorPossuiTecladoFieldSpecified;
            }
            set {
                this.indicadorPossuiTecladoFieldSpecified = value;
                this.RaisePropertyChanged("indicadorPossuiTecladoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public bool indicadorPossuiTrilha {
            get {
                return this.indicadorPossuiTrilhaField;
            }
            set {
                this.indicadorPossuiTrilhaField = value;
                this.RaisePropertyChanged("indicadorPossuiTrilha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool indicadorPossuiTrilhaSpecified {
            get {
                return this.indicadorPossuiTrilhaFieldSpecified;
            }
            set {
                this.indicadorPossuiTrilhaFieldSpecified = value;
                this.RaisePropertyChanged("indicadorPossuiTrilhaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string nomeGrupoSolucaoCaptura {
            get {
                return this.nomeGrupoSolucaoCapturaField;
            }
            set {
                this.nomeGrupoSolucaoCapturaField = value;
                this.RaisePropertyChanged("nomeGrupoSolucaoCaptura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string nomeTecnologia {
            get {
                return this.nomeTecnologiaField;
            }
            set {
                this.nomeTecnologiaField = value;
                this.RaisePropertyChanged("nomeTecnologia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public long numeroAcesso {
            get {
                return this.numeroAcessoField;
            }
            set {
                this.numeroAcessoField = value;
                this.RaisePropertyChanged("numeroAcesso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroAcessoSpecified {
            get {
                return this.numeroAcessoFieldSpecified;
            }
            set {
                this.numeroAcessoFieldSpecified = value;
                this.RaisePropertyChanged("numeroAcessoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string numeroLogico {
            get {
                return this.numeroLogicoField;
            }
            set {
                this.numeroLogicoField = value;
                this.RaisePropertyChanged("numeroLogico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string numeroSerie {
            get {
                return this.numeroSerieField;
            }
            set {
                this.numeroSerieField = value;
                this.RaisePropertyChanged("numeroSerie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string siglaTipoTerminal {
            get {
                return this.siglaTipoTerminalField;
            }
            set {
                this.siglaTipoTerminalField = value;
                this.RaisePropertyChanged("siglaTipoTerminal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string codigoSIMCard {
            get {
                return this.codigoSIMCardField;
            }
            set {
                this.codigoSIMCardField = value;
                this.RaisePropertyChanged("codigoSIMCard");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string indicadorCanalOrigem {
            get {
                return this.indicadorCanalOrigemField;
            }
            set {
                this.indicadorCanalOrigemField = value;
                this.RaisePropertyChanged("indicadorCanalOrigem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.cielo.com.br/operacao/logistica/equipamento/v9/consultarterminalde" +
        "talhado")]
    public partial class DadosClienteType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long codigoClienteField;
        
        private bool codigoClienteFieldSpecified;
        
        private string codigoLojaEstabelecimentoField;
        
        private string codigoTipoPessoaField;
        
        private string descricaoNomeComprovanteField;
        
        private bool indicadorComercioEletronicoField;
        
        private bool indicadorComercioEletronicoFieldSpecified;
        
        private string nomeClienteField;
        
        private string nomeFantasiaField;
        
        private string nomeRazaoSocialField;
        
        private string siglaBloqueioInternacionalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long codigoCliente {
            get {
                return this.codigoClienteField;
            }
            set {
                this.codigoClienteField = value;
                this.RaisePropertyChanged("codigoCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoClienteSpecified {
            get {
                return this.codigoClienteFieldSpecified;
            }
            set {
                this.codigoClienteFieldSpecified = value;
                this.RaisePropertyChanged("codigoClienteSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
        public string codigoLojaEstabelecimento {
            get {
                return this.codigoLojaEstabelecimentoField;
            }
            set {
                this.codigoLojaEstabelecimentoField = value;
                this.RaisePropertyChanged("codigoLojaEstabelecimento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string codigoTipoPessoa {
            get {
                return this.codigoTipoPessoaField;
            }
            set {
                this.codigoTipoPessoaField = value;
                this.RaisePropertyChanged("codigoTipoPessoa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string descricaoNomeComprovante {
            get {
                return this.descricaoNomeComprovanteField;
            }
            set {
                this.descricaoNomeComprovanteField = value;
                this.RaisePropertyChanged("descricaoNomeComprovante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool indicadorComercioEletronico {
            get {
                return this.indicadorComercioEletronicoField;
            }
            set {
                this.indicadorComercioEletronicoField = value;
                this.RaisePropertyChanged("indicadorComercioEletronico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool indicadorComercioEletronicoSpecified {
            get {
                return this.indicadorComercioEletronicoFieldSpecified;
            }
            set {
                this.indicadorComercioEletronicoFieldSpecified = value;
                this.RaisePropertyChanged("indicadorComercioEletronicoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string nomeCliente {
            get {
                return this.nomeClienteField;
            }
            set {
                this.nomeClienteField = value;
                this.RaisePropertyChanged("nomeCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string nomeFantasia {
            get {
                return this.nomeFantasiaField;
            }
            set {
                this.nomeFantasiaField = value;
                this.RaisePropertyChanged("nomeFantasia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string nomeRazaoSocial {
            get {
                return this.nomeRazaoSocialField;
            }
            set {
                this.nomeRazaoSocialField = value;
                this.RaisePropertyChanged("nomeRazaoSocial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string siglaBloqueioInternacional {
            get {
                return this.siglaBloqueioInternacionalField;
            }
            set {
                this.siglaBloqueioInternacionalField = value;
                this.RaisePropertyChanged("siglaBloqueioInternacional");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.cielo.com.br/operacao/logistica/equipamento/v9/consultarterminalde" +
        "talhado")]
    public partial class DadosBaixaTecnicaType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoRetornoUltimaInicializacaoBaixaTecnicaField;
        
        private string codigoTipoBaixaTecnicaField;
        
        private System.DateTime dataUltimaBaixaTecnicaField;
        
        private bool dataUltimaBaixaTecnicaFieldSpecified;
        
        private System.DateTime horaUltimaBaixaTecnicaField;
        
        private bool horaUltimaBaixaTecnicaFieldSpecified;
        
        private string mensagemRetornoUltimaInicializacaoBaixaTecnicaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string codigoRetornoUltimaInicializacaoBaixaTecnica {
            get {
                return this.codigoRetornoUltimaInicializacaoBaixaTecnicaField;
            }
            set {
                this.codigoRetornoUltimaInicializacaoBaixaTecnicaField = value;
                this.RaisePropertyChanged("codigoRetornoUltimaInicializacaoBaixaTecnica");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
        public string codigoTipoBaixaTecnica {
            get {
                return this.codigoTipoBaixaTecnicaField;
            }
            set {
                this.codigoTipoBaixaTecnicaField = value;
                this.RaisePropertyChanged("codigoTipoBaixaTecnica");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime dataUltimaBaixaTecnica {
            get {
                return this.dataUltimaBaixaTecnicaField;
            }
            set {
                this.dataUltimaBaixaTecnicaField = value;
                this.RaisePropertyChanged("dataUltimaBaixaTecnica");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataUltimaBaixaTecnicaSpecified {
            get {
                return this.dataUltimaBaixaTecnicaFieldSpecified;
            }
            set {
                this.dataUltimaBaixaTecnicaFieldSpecified = value;
                this.RaisePropertyChanged("dataUltimaBaixaTecnicaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time", Order=3)]
        public System.DateTime horaUltimaBaixaTecnica {
            get {
                return this.horaUltimaBaixaTecnicaField;
            }
            set {
                this.horaUltimaBaixaTecnicaField = value;
                this.RaisePropertyChanged("horaUltimaBaixaTecnica");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool horaUltimaBaixaTecnicaSpecified {
            get {
                return this.horaUltimaBaixaTecnicaFieldSpecified;
            }
            set {
                this.horaUltimaBaixaTecnicaFieldSpecified = value;
                this.RaisePropertyChanged("horaUltimaBaixaTecnicaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string mensagemRetornoUltimaInicializacaoBaixaTecnica {
            get {
                return this.mensagemRetornoUltimaInicializacaoBaixaTecnicaField;
            }
            set {
                this.mensagemRetornoUltimaInicializacaoBaixaTecnicaField = value;
                this.RaisePropertyChanged("mensagemRetornoUltimaInicializacaoBaixaTecnica");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.cielo.com.br/operacao/logistica/equipamento/v9/consultarterminalde" +
        "talhado")]
    public partial class DadosAtualizacaoPaginaType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoNoAtualizacaoPaginaField;
        
        private System.DateTime dataAtualizacaoPaginaField;
        
        private bool dataAtualizacaoPaginaFieldSpecified;
        
        private System.DateTime horaAtualizacaoPaginaField;
        
        private bool horaAtualizacaoPaginaFieldSpecified;
        
        private string indicadorAtualizacaoPaginaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string codigoNoAtualizacaoPagina {
            get {
                return this.codigoNoAtualizacaoPaginaField;
            }
            set {
                this.codigoNoAtualizacaoPaginaField = value;
                this.RaisePropertyChanged("codigoNoAtualizacaoPagina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime dataAtualizacaoPagina {
            get {
                return this.dataAtualizacaoPaginaField;
            }
            set {
                this.dataAtualizacaoPaginaField = value;
                this.RaisePropertyChanged("dataAtualizacaoPagina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataAtualizacaoPaginaSpecified {
            get {
                return this.dataAtualizacaoPaginaFieldSpecified;
            }
            set {
                this.dataAtualizacaoPaginaFieldSpecified = value;
                this.RaisePropertyChanged("dataAtualizacaoPaginaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time", Order=2)]
        public System.DateTime horaAtualizacaoPagina {
            get {
                return this.horaAtualizacaoPaginaField;
            }
            set {
                this.horaAtualizacaoPaginaField = value;
                this.RaisePropertyChanged("horaAtualizacaoPagina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool horaAtualizacaoPaginaSpecified {
            get {
                return this.horaAtualizacaoPaginaFieldSpecified;
            }
            set {
                this.horaAtualizacaoPaginaFieldSpecified = value;
                this.RaisePropertyChanged("horaAtualizacaoPaginaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string indicadorAtualizacaoPagina {
            get {
                return this.indicadorAtualizacaoPaginaField;
            }
            set {
                this.indicadorAtualizacaoPaginaField = value;
                this.RaisePropertyChanged("indicadorAtualizacaoPagina");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.cielo.com.br/operacao/logistica/equipamento/v9/consultarterminalde" +
        "talhado")]
    public partial class ConsultarTerminalDetalhadoRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroLogicoField;
        
        private string descricaoTipoTecnologiaField;
        
        private string nomeSistemaSolicitanteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string numeroLogico {
            get {
                return this.numeroLogicoField;
            }
            set {
                this.numeroLogicoField = value;
                this.RaisePropertyChanged("numeroLogico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string descricaoTipoTecnologia {
            get {
                return this.descricaoTipoTecnologiaField;
            }
            set {
                this.descricaoTipoTecnologiaField = value;
                this.RaisePropertyChanged("descricaoTipoTecnologia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string nomeSistemaSolicitante {
            get {
                return this.nomeSistemaSolicitanteField;
            }
            set {
                this.nomeSistemaSolicitanteField = value;
                this.RaisePropertyChanged("nomeSistemaSolicitante");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.cielo.com.br/operacao/logistica/equipamento/v9/consultarterminalde" +
        "talhado", ConfigurationName="svcOsbConsultaTerminal.Equipamento_consultarTerminalDetalhadoServicePortType")]
    public interface Equipamento_consultarTerminalDetalhadoServicePortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.cielo.com.br/operacao/logistica/equipamento/v9/consultarterminalde" +
            "talhado", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.Fault), Action="http://service.cielo.com.br/operacao/logistica/equipamento/v9/consultarterminalde" +
            "talhado", Name="fault", Namespace="http://canonico.cielo.com.br/comum/v1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.consultarTerminalDetalhadoResponse consultarTerminalDetalhado(Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.consultarTerminalDetalhadoRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a operação tem vários valores de retorno.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.cielo.com.br/operacao/logistica/equipamento/v9/consultarterminalde" +
            "talhado", ReplyAction="*")]
        System.Threading.Tasks.Task<Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.consultarTerminalDetalhadoResponse> consultarTerminalDetalhadoAsync(Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.consultarTerminalDetalhadoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/governancasoa/comum/v1")]
    public partial class CieloSoapHeaderType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object itemField;
        
        private string recursoField;
        
        private string realmField;
        
        private IdentificacaoRequestType identificacaoRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("token", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("usuario", typeof(UsuarioType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string recurso {
            get {
                return this.recursoField;
            }
            set {
                this.recursoField = value;
                this.RaisePropertyChanged("recurso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string realm {
            get {
                return this.realmField;
            }
            set {
                this.realmField = value;
                this.RaisePropertyChanged("realm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public IdentificacaoRequestType identificacaoRequest {
            get {
                return this.identificacaoRequestField;
            }
            set {
                this.identificacaoRequestField = value;
                this.RaisePropertyChanged("identificacaoRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/governancasoa/comum/v1")]
    public partial class UsuarioType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string senhaField;
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
                this.RaisePropertyChanged("senha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/governancasoa/comum/v1")]
    public partial class IdentificacaoRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nomeSistemaField;
        
        private string nomeTipoChamadaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nomeSistema {
            get {
                return this.nomeSistemaField;
            }
            set {
                this.nomeSistemaField = value;
                this.RaisePropertyChanged("nomeSistema");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nomeTipoChamada {
            get {
                return this.nomeTipoChamadaField;
            }
            set {
                this.nomeTipoChamadaField = value;
                this.RaisePropertyChanged("nomeTipoChamada");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarTerminalDetalhadoRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://canonico.cielo.com.br/governancasoa/comum/v1")]
        public Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.CieloSoapHeaderType cieloSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultarTerminalDetalhadoRequest", Namespace="http://service.cielo.com.br/operacao/logistica/equipamento/v9/consultarterminalde" +
            "talhado", Order=0)]
        public Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.ConsultarTerminalDetalhadoRequestType consultarTerminalDetalhadoRequest1;
        
        public consultarTerminalDetalhadoRequest() {
        }
        
        public consultarTerminalDetalhadoRequest(Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.CieloSoapHeaderType cieloSoapHeader, Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.ConsultarTerminalDetalhadoRequestType consultarTerminalDetalhadoRequest1) {
            this.cieloSoapHeader = cieloSoapHeader;
            this.consultarTerminalDetalhadoRequest1 = consultarTerminalDetalhadoRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarTerminalDetalhadoResponse", WrapperNamespace="http://service.cielo.com.br/operacao/logistica/equipamento/v9/consultarterminalde" +
        "talhado", IsWrapped=true)]
    public partial class consultarTerminalDetalhadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/operacao/logistica/equipamento/v9/consultarterminalde" +
            "talhado", Order=0)]
        public Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.DadosAtualizacaoPaginaType dadosAtualizacaoPagina;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/operacao/logistica/equipamento/v9/consultarterminalde" +
            "talhado", Order=1)]
        public Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.DadosBaixaTecnicaType dadosBaixaTecnica;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/operacao/logistica/equipamento/v9/consultarterminalde" +
            "talhado", Order=2)]
        public Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.DadosClienteType dadosCliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/operacao/logistica/equipamento/v9/consultarterminalde" +
            "talhado", Order=3)]
        public Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.DadosEquipamentoType dadosEquipamento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/operacao/logistica/equipamento/v9/consultarterminalde" +
            "talhado", Order=4)]
        public Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.DadosGrupoSolucaoType dadosGrupoSolucao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/operacao/logistica/equipamento/v9/consultarterminalde" +
            "talhado", Order=5)]
        public Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.DadosRetornoType dadosRetorno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/operacao/logistica/equipamento/v9/consultarterminalde" +
            "talhado", Order=6)]
        public Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.DadosUltimaInicializacaoType dadosUltimaInicializacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/operacao/logistica/equipamento/v9/consultarterminalde" +
            "talhado", Order=7)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dadosProcessamento", IsNullable=false)]
        public Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.DadosProcessamentoType[] listaDadosProcessamento;
        
        public consultarTerminalDetalhadoResponse() {
        }
        
        public consultarTerminalDetalhadoResponse(Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.DadosAtualizacaoPaginaType dadosAtualizacaoPagina, Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.DadosBaixaTecnicaType dadosBaixaTecnica, Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.DadosClienteType dadosCliente, Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.DadosEquipamentoType dadosEquipamento, Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.DadosGrupoSolucaoType dadosGrupoSolucao, Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.DadosRetornoType dadosRetorno, Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.DadosUltimaInicializacaoType dadosUltimaInicializacao, Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.DadosProcessamentoType[] listaDadosProcessamento) {
            this.dadosAtualizacaoPagina = dadosAtualizacaoPagina;
            this.dadosBaixaTecnica = dadosBaixaTecnica;
            this.dadosCliente = dadosCliente;
            this.dadosEquipamento = dadosEquipamento;
            this.dadosGrupoSolucao = dadosGrupoSolucao;
            this.dadosRetorno = dadosRetorno;
            this.dadosUltimaInicializacao = dadosUltimaInicializacao;
            this.listaDadosProcessamento = listaDadosProcessamento;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Equipamento_consultarTerminalDetalhadoServicePortTypeChannel : Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.Equipamento_consultarTerminalDetalhadoServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Equipamento_consultarTerminalDetalhadoServicePortTypeClient : System.ServiceModel.ClientBase<Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.Equipamento_consultarTerminalDetalhadoServicePortType>, Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.Equipamento_consultarTerminalDetalhadoServicePortType {
        
        public Equipamento_consultarTerminalDetalhadoServicePortTypeClient() {
        }
        
        public Equipamento_consultarTerminalDetalhadoServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Equipamento_consultarTerminalDetalhadoServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Equipamento_consultarTerminalDetalhadoServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Equipamento_consultarTerminalDetalhadoServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.consultarTerminalDetalhadoResponse Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.Equipamento_consultarTerminalDetalhadoServicePortType.consultarTerminalDetalhado(Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.consultarTerminalDetalhadoRequest request) {
            return base.Channel.consultarTerminalDetalhado(request);
        }
        
        public Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.DadosAtualizacaoPaginaType consultarTerminalDetalhado(Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.CieloSoapHeaderType cieloSoapHeader, Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.ConsultarTerminalDetalhadoRequestType consultarTerminalDetalhadoRequest1, out Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.DadosBaixaTecnicaType dadosBaixaTecnica, out Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.DadosClienteType dadosCliente, out Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.DadosEquipamentoType dadosEquipamento, out Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.DadosGrupoSolucaoType dadosGrupoSolucao, out Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.DadosRetornoType dadosRetorno, out Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.DadosUltimaInicializacaoType dadosUltimaInicializacao, out Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.DadosProcessamentoType[] listaDadosProcessamento) {
            Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.consultarTerminalDetalhadoRequest inValue = new Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.consultarTerminalDetalhadoRequest();
            inValue.cieloSoapHeader = cieloSoapHeader;
            inValue.consultarTerminalDetalhadoRequest1 = consultarTerminalDetalhadoRequest1;
            Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.consultarTerminalDetalhadoResponse retVal = ((Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.Equipamento_consultarTerminalDetalhadoServicePortType)(this)).consultarTerminalDetalhado(inValue);
            dadosBaixaTecnica = retVal.dadosBaixaTecnica;
            dadosCliente = retVal.dadosCliente;
            dadosEquipamento = retVal.dadosEquipamento;
            dadosGrupoSolucao = retVal.dadosGrupoSolucao;
            dadosRetorno = retVal.dadosRetorno;
            dadosUltimaInicializacao = retVal.dadosUltimaInicializacao;
            listaDadosProcessamento = retVal.listaDadosProcessamento;
            return retVal.dadosAtualizacaoPagina;
        }
        
        public System.Threading.Tasks.Task<Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.consultarTerminalDetalhadoResponse> consultarTerminalDetalhadoAsync(Senac.Fecomercio.ControlaWebServices.svcOsbConsultaTerminal.consultarTerminalDetalhadoRequest request) {
            return base.Channel.consultarTerminalDetalhadoAsync(request);
        }
    }
}
