//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;
using System.Xml;
using System.Windows.Forms;
using System.Configuration;

namespace Visanet.WebServices.ProxyServer
{
    /// <summary>
    /// <b>Objetivo:</b>
    /// - Intermediar comunicação com outras empresas.
    /// 
    /// <b>Lógica (Corpo do Programa):</b>
    /// - Atua como intermediário na comunicação WebService entre a Cielo e outras empresas.
    /// 
    /// <b>Subprogramas:</b>
    /// - Não aplicável.
    /// </summary>

    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "GtecService_MIBinding", Namespace = "urn:visanet:legancy:gtec:opl")]

    public partial class GtecService_MIService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback GtecService_MIOperationCompleted;

        /// <summary>
        /// <b>Objetivo:</b>
        /// - Construtor da classe.
        /// 
        /// <b>Lógica (Corpo do Programa):</b>
        /// - Leitura de parâmetros de execução.
        /// 
        /// <b>Subprogramas:</b>
        /// - Não aplicável.
        /// </summary>
        public GtecService_MIService()
        {

            string sProtocolo = ConfigurationManager.AppSettings["xi_protocolo"];
            string sServidor = ConfigurationManager.AppSettings["xi_servidor"];
            string sPorta = ConfigurationManager.AppSettings["xi_porta"];
            string sBusinessSystem = ConfigurationManager.AppSettings["xi_businesssystem"];

            this.Url = sProtocolo.Trim() + "://" + sServidor.Trim() + ":" + sPorta.Trim() + "/XISOAPAdapter/MessageServlet?channel=:Gtec_" + sBusinessSystem + ":Gtec_Soap_" +
                "OL_Sender&version=3.0&Sender.Service=Gtec_" + sBusinessSystem + "&Interface=urn%3Avisanet%3Alegancy%3" +
                "Agtec%3Aopl%5EGtecService_MI";
        }

        /// <remarks/>
        public event GtecService_MICompletedEventHandler GtecService_MICompleted;

        /// <summary>
        /// <b>Objetivo:</b>
        /// - Executar método webservice.
        /// 
        /// <b>Lógica (Corpo do Programa):</b>
        /// - Realiza chamada de método webservice.
        /// - Transmite objeto de transporte.
        /// - Retorna resposta recebida.
        /// 
        /// <b>Subprogramas:</b>
        /// - Não aplicável.
        /// </summary>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("responseGtec_MT", Namespace = "urn:visanet:legancy:gtec:opl")]
        public Return_DT GtecService_MI([System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:visanet:legancy:gtec:opl")] msgGtec_DT msgGtec_MT)
        {
            object[] results = this.Invoke("GtecService_MI", new object[] {
                    msgGtec_MT});
            return ((Return_DT)(results[0]));
        }

        /// <summary>
        /// <b>Objetivo:</b>
        /// - Executar método webservice.
        /// 
        /// <b>Lógica (Corpo do Programa):</b>
        /// - Realiza chamada de método webservice.
        /// - Transmite objeto de transporte.
        /// - Retorna resposta recebida.
        /// 
        /// <b>Subprogramas:</b>
        /// - Não aplicável.
        /// </summary>

        //[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        //[return: System.Xml.Serialization.XmlElementAttribute("responseGtec_MT", Namespace = "urn:visanet:legancy:gtec:opl")]
        //public Return_DT GtecService_MI2([System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:visanet:legancy:gtec:opl")] msgGtec_DT2 msgGtec_MT)
        //{
        //    object[] results = this.Invoke("GtecService_MI2", new object[] {
        //            msgGtec_MT});
        //    return ((Return_DT)(results[0]));
        //}

        /// <summary>
        /// <b>Objetivo:</b>
        /// - Executar método webservice, de forma assíncrona.
        /// 
        /// <b>Lógica (Corpo do Programa):</b>
        /// - Permite execução assíncrona do método webservice.
        /// 
        /// <b>Subprogramas:</b>
        /// - Não aplicável.
        /// </summary>
        public System.IAsyncResult BeginGtecService_MI(msgGtec_DT msgGtec_MT, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GtecService_MI", new object[] {
                    msgGtec_MT}, callback, asyncState);
        }

        /// <summary>
        /// <b>Objetivo:</b>
        /// - Auxiliar para execução assíncrona de método webservice.
        /// 
        /// <b>Lógica (Corpo do Programa):</b>
        /// - Permite execução assíncrona do método webservice.
        /// 
        /// <b>Subprogramas:</b>
        /// - Não aplicável.
        /// </summary>
        public Return_DT EndGtecService_MI(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((Return_DT)(results[0]));
        }

        /// <summary>
        /// <b>Objetivo:</b>
        /// - Auxiliar para execução assíncrona de método webservice.
        /// 
        /// <b>Lógica (Corpo do Programa):</b>
        /// - Permite execução assíncrona do método webservice.
        /// 
        /// <b>Subprogramas:</b>
        /// - Não aplicável.
        /// </summary>
        public void GtecService_MIAsync(msgGtec_DT msgGtec_MT)
        {
            this.GtecService_MIAsync(msgGtec_MT, null);
        }

        /// <summary>
        /// <b>Objetivo:</b>
        /// - Auxiliar para execução assíncrona de método webservice.
        /// 
        /// <b>Lógica (Corpo do Programa):</b>
        /// - Permite execução assíncrona do método webservice.
        /// 
        /// <b>Subprogramas:</b>
        /// - Não aplicável.
        /// </summary>
        public void GtecService_MIAsync(msgGtec_DT msgGtec_MT, object userState)
        {
            if ((this.GtecService_MIOperationCompleted == null))
            {
                this.GtecService_MIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGtecService_MIOperationCompleted);
            }
            this.InvokeAsync("GtecService_MI", new object[] {
                    msgGtec_MT}, this.GtecService_MIOperationCompleted, userState);
        }

        /// <summary>
        /// <b>Objetivo:</b>
        /// - Auxiliar para execução assíncrona de método webservice.
        /// 
        /// <b>Lógica (Corpo do Programa):</b>
        /// - Permite execução assíncrona do método webservice.
        /// 
        /// <b>Subprogramas:</b>
        /// - Não aplicável.
        /// </summary>
        private void OnGtecService_MIOperationCompleted(object arg)
        {
            if ((this.GtecService_MICompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GtecService_MICompleted(this, new GtecService_MICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <summary>
        /// <b>Objetivo:</b>
        /// - Auxiliar para execução assíncrona de método webservice.
        /// 
        /// <b>Lógica (Corpo do Programa):</b>
        /// - Permite execução assíncrona do método webservice.
        /// 
        /// <b>Subprogramas:</b>
        /// - Não aplicável.
        /// </summary>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <summary>
    /// <b>Objetivo:</b>
    /// - Manter atributos.
    /// 
    /// <b>Lógica (Corpo do Programa):</b>
    /// - Mantém propriedades necessárias para transmissão de chamado GTEC.
    /// 
    /// <b>Subprogramas:</b>
    /// - Não aplicável.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:visanet:legancy:gtec:opl")]
    public partial class msgGtec_DT
    {

        private Cliente_DT clienteField;

        private Equipamento_DT equipamentoField;

        private Equipamento_DT equipamentoDesinstalacaoField;

        private Cobranca_DT cobrancaField;

        private Gtec_DT gtecField;

        private FeiraEventos_DT feirasEventosField;

        private string codigoAcaoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Cliente_DT Cliente
        {
            get
            {
                return this.clienteField;
            }
            set
            {
                this.clienteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Equipamento_DT Equipamento
        {
            get
            {
                return this.equipamentoField;
            }
            set
            {
                this.equipamentoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Equipamento_DT EquipamentoDesinstalacao
        {
            get
            {
                return this.equipamentoDesinstalacaoField;
            }
            set
            {
                this.equipamentoDesinstalacaoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Cobranca_DT Cobranca
        {
            get
            {
                return this.cobrancaField;
            }
            set
            {
                this.cobrancaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Gtec_DT Gtec
        {
            get
            {
                return this.gtecField;
            }
            set
            {
                this.gtecField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FeiraEventos_DT FeirasEventos
        {
            get
            {
                return this.feirasEventosField;
            }
            set
            {
                this.feirasEventosField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
        public string codigoAcao
        {
            get
            {
                return this.codigoAcaoField;
            }
            set
            {
                this.codigoAcaoField = value;
            }
        }
    }

    /// <summary>
    /// <b>Objetivo:</b>
    /// - Manter atributos.
    /// 
    /// <b>Lógica (Corpo do Programa):</b>
    /// - Mantém propriedades necessárias para transmissão de chamado GTEC.
    /// 
    /// <b>Subprogramas:</b>
    /// - Não aplicável.
    /// </summary>

    //[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    //[System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:visanet:legancy:gtec:opl")]
    //public partial class msgGtec_DT2
    //{
    //
    //    private Cliente_DT2 clienteField;
    //
    //    private Equipamento_DT equipamentoField;
    //
    //    private Equipamento_DT equipamentoDesinstalacaoField;
    //
    //    private Cobranca_DT cobrancaField;
    //
    //    private Gtec_DT gtecField;
    //
    //    private FeiraEventos_DT feirasEventosField;
    //
    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    public Cliente_DT2 Cliente
    //    {
    //        get
    //        {
    //            return this.clienteField;
    //        }
    //        set
    //        {
    //            this.clienteField = value;
    //        }
    //    }
    //
    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    public Equipamento_DT Equipamento
    //    {
    //        get
    //        {
    //            return this.equipamentoField;
    //        }
    //        set
    //        {
    //            this.equipamentoField = value;
    //        }
    //    }
    //
    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    public Equipamento_DT EquipamentoDesinstalacao
    //    {
    //        get
    //        {
    //            return this.equipamentoDesinstalacaoField;
    //        }
    //        set
    //        {
    //            this.equipamentoDesinstalacaoField = value;
    //        }
    //    }
    //
    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    public Cobranca_DT Cobranca
    //    {
    //        get
    //        {
    //            return this.cobrancaField;
    //        }
    //        set
    //        {
    //            this.cobrancaField = value;
    //        }
    //    }
    //
    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    public Gtec_DT Gtec
    //    {
    //        get
    //        {
    //            return this.gtecField;
    //        }
    //        set
    //        {
    //            this.gtecField = value;
    //        }
    //    }
    //
    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    public FeiraEventos_DT FeirasEventos
    //    {
    //        get
    //        {
    //            return this.feirasEventosField;
    //        }
    //        set
    //        {
    //            this.feirasEventosField = value;
    //        }
    //    }
    //}

    /// <summary>
    /// <b>Objetivo:</b>
    /// - Manter atributos.
    /// 
    /// <b>Lógica (Corpo do Programa):</b>
    /// - Mantém propriedades necessárias para transmissão de dados de cliente.
    /// 
    /// <b>Subprogramas:</b>
    /// - Não aplicável.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:visanet:legancy:gtec:opl")]
    public partial class Cliente_DT
    {

        private string codigoClienteField = "";

        private string nomeFantasiaField = "";

        private string razaoSocialField = "";

        private string contatoField = "";

        private string telefoneField = "";

        private string horarioFuncionamentoField = "";

        private string ramoAtividadeField = "";

        private string enderecoField = "";

        private string bairroField = "";

        private string cidadeField = "";

        private string ufField = "";

        private string cEPField = "";

        private string segmentoField = "";

        private string pacoteField = "";

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodigoCliente
        {
            get
            {
                return this.codigoClienteField;
            }
            set
            {
                this.codigoClienteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NomeFantasia
        {
            get
            {
                return this.nomeFantasiaField;
            }
            set
            {
                this.nomeFantasiaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RazaoSocial
        {
            get
            {
                return this.razaoSocialField;
            }
            set
            {
                this.razaoSocialField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Contato
        {
            get
            {
                return this.contatoField;
            }
            set
            {
                this.contatoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Telefone
        {
            get
            {
                return this.telefoneField;
            }
            set
            {
                this.telefoneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HorarioFuncionamento
        {
            get
            {
                return this.horarioFuncionamentoField;
            }
            set
            {
                this.horarioFuncionamentoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RamoAtividade
        {
            get
            {
                return this.ramoAtividadeField;
            }
            set
            {
                this.ramoAtividadeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Endereco
        {
            get
            {
                return this.enderecoField;
            }
            set
            {
                this.enderecoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Bairro
        {
            get
            {
                return this.bairroField;
            }
            set
            {
                this.bairroField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Cidade
        {
            get
            {
                return this.cidadeField;
            }
            set
            {
                this.cidadeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UF
        {
            get
            {
                return this.ufField;
            }
            set
            {
                this.ufField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CEP
        {
            get
            {
                return this.cEPField;
            }
            set
            {
                this.cEPField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Segmento
        {
            get
            {
                return this.segmentoField;
            }
            set
            {
                this.segmentoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Pacote
        {
            get
            {
                return this.pacoteField;
            }
            set
            {
                this.pacoteField = value;
            }
        }
    }

    /// <summary>
    /// <b>Objetivo:</b>
    /// - Manter atributos.
    /// 
    /// <b>Lógica (Corpo do Programa):</b>
    /// - Mantém propriedades necessárias para transmissão de dados de cliente.
    /// 
    /// <b>Subprogramas:</b>
    /// - Não aplicável.
    /// </summary>

    //[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    //[System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:visanet:legancy:gtec:opl")]
    //public partial class Cliente_DT2
    //{
    //
    //    private string codigoClienteField = "";
    //
    //    private string nomeFantasiaField = "";
    //
    //    private string razaoSocialField = "";
    //
    //    private string contatoField = "";
    //
    //    private string telefoneField = "";
    //
    //    private string horarioFuncionamentoField = "";
    //
    //    private string ramoAtividadeField = "";
    //
    //    private string enderecoField = "";
    //
    //    private string bairroField = "";
    //
    //    private string cidadeField = "";
    //
    //    private string ufField = "";
    //
    //    private string cEPField = "";
    //
    //    private string segmentoField = "";
    //
    //    private string pacoteField = "";
    //
    //    private string cnpjField = "";
    //
    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    public string CodigoCliente
    //    {
    //        get
    //        {
    //            return this.codigoClienteField;
    //        }
    //        set
    //        {
    //            this.codigoClienteField = value;
    //        }
    //    }
    //
    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    public string NomeFantasia
    //    {
    //        get
    //        {
    //            return this.nomeFantasiaField;
    //        }
    //        set
    //        {
    //            this.nomeFantasiaField = value;
    //        }
    //    }
    //
    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    public string RazaoSocial
    //    {
    //        get
    //        {
    //            return this.razaoSocialField;
    //        }
    //        set
    //        {
    //            this.razaoSocialField = value;
    //        }
    //    }
    //
    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    public string Contato
    //    {
    //        get
    //        {
    //            return this.contatoField;
    //        }
    //        set
    //        {
    //            this.contatoField = value;
    //        }
    //    }
    //
    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    public string Telefone
    //    {
    //        get
    //        {
    //            return this.telefoneField;
    //        }
    //        set
    //        {
    //            this.telefoneField = value;
    //        }
    //    }
    //
    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    public string HorarioFuncionamento
    //    {
    //        get
    //        {
    //            return this.horarioFuncionamentoField;
    //        }
    //        set
    //        {
    //            this.horarioFuncionamentoField = value;
    //        }
    //    }
    //
    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    public string RamoAtividade
    //    {
    //        get
    //        {
    //            return this.ramoAtividadeField;
    //        }
    //        set
    //        {
    //            this.ramoAtividadeField = value;
    //        }
    //    }
    //
    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    public string Endereco
    //    {
    //        get
    //        {
    //            return this.enderecoField;
    //        }
    //        set
    //        {
    //            this.enderecoField = value;
    //        }
    //    }
    //
    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    public string Bairro
    //    {
    //        get
    //        {
    //            return this.bairroField;
    //        }
    //        set
    //        {
    //            this.bairroField = value;
    //        }
    //    }
    //
    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    public string Cidade
    //    {
    //        get
    //        {
    //            return this.cidadeField;
    //        }
    //        set
    //        {
    //            this.cidadeField = value;
    //        }
    //    }
    //
    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    public string UF
    //    {
    //        get
    //        {
    //            return this.ufField;
    //        }
    //        set
    //        {
    //            this.ufField = value;
    //        }
    //    }
    //
    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    public string CEP
    //    {
    //        get
    //        {
    //            return this.cEPField;
    //        }
    //        set
    //        {
    //            this.cEPField = value;
    //        }
    //    }
    //
    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    public string Segmento
    //    {
    //        get
    //        {
    //            return this.segmentoField;
    //        }
    //        set
    //        {
    //            this.segmentoField = value;
    //        }
    //    }
    //
    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    public string Pacote
    //    {
    //        get
    //        {
    //            return this.pacoteField;
    //        }
    //        set
    //        {
    //            this.pacoteField = value;
    //        }
    //    }
    //
    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    public string Cnpj
    //    {
    //        get
    //        {
    //            return this.cnpjField;
    //        }
    //        set
    //        {
    //            this.cnpjField = value;
    //        }
    //    }
    //}

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:visanet:legancy:gtec:opl")]
    public partial class Return_DT
    {

        private int codigoField;

        private string descricaoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descricao
        {
            get
            {
                return this.descricaoField;
            }
            set
            {
                this.descricaoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:visanet:legancy:gtec:opl")]
    public partial class FeiraEventos_DT
    {

        private string nomeFeiraField = "";

        private string localFeiraField = "";

        private System.DateTime dataInicioFeiraField;

        private System.DateTime dataFimFeiraField;

        private System.DateTime dtHrAgendamentoInstalacaoField;

        private System.DateTime dtHrAgendamentoDesinstalacaoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NomeFeira
        {
            get
            {
                return this.nomeFeiraField;
            }
            set
            {
                this.nomeFeiraField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LocalFeira
        {
            get
            {
                return this.localFeiraField;
            }
            set
            {
                this.localFeiraField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime DataInicioFeira
        {
            get
            {
                return this.dataInicioFeiraField;
            }
            set
            {
                this.dataInicioFeiraField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime DataFimFeira
        {
            get
            {
                return this.dataFimFeiraField;
            }
            set
            {
                this.dataFimFeiraField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime DtHrAgendamentoInstalacao
        {
            get
            {
                return this.dtHrAgendamentoInstalacaoField;
            }
            set
            {
                this.dtHrAgendamentoInstalacaoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime DtHrAgendamentoDesinstalacao
        {
            get
            {
                return this.dtHrAgendamentoDesinstalacaoField;
            }
            set
            {
                this.dtHrAgendamentoDesinstalacaoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:visanet:legancy:gtec:opl")]
    public partial class Kit_DT
    {

        private int codigoKitField;

        private bool codigoKitFieldSpecified;

        private string descricaoKitField = "";

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int CodigoKit
        {
            get
            {
                return this.codigoKitField;
            }
            set
            {
                this.codigoKitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodigoKitSpecified
        {
            get
            {
                return this.codigoKitFieldSpecified;
            }
            set
            {
                this.codigoKitFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DescricaoKit
        {
            get
            {
                return this.descricaoKitField;
            }
            set
            {
                this.descricaoKitField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:visanet:legancy:gtec:opl")]
    public partial class Gtec_DT
    {

        private string codOperadorField = "";

        private string tipoServicoField = "";

        private string chamadoGTECField = "";

        private System.DateTime dataHoraSLAField;

        private string ocorrenciaManutField = "";

        private string ocorrenciaField = "";

        private string referenciaField = "";

        private string servicoContratadoField = "";

        private string filialDesignadaField = "";

        private string observacaoField = "";

        private string codigoAcessoField = "";

        private Kit_DT[] kitSinalizacaoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodOperador
        {
            get
            {
                return this.codOperadorField;
            }
            set
            {
                this.codOperadorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TipoServico
        {
            get
            {
                return this.tipoServicoField;
            }
            set
            {
                this.tipoServicoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ChamadoGTEC
        {
            get
            {
                return this.chamadoGTECField;
            }
            set
            {
                this.chamadoGTECField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime DataHoraSLA
        {
            get
            {
                return this.dataHoraSLAField;
            }
            set
            {
                this.dataHoraSLAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OcorrenciaManut
        {
            get
            {
                return this.ocorrenciaManutField;
            }
            set
            {
                this.ocorrenciaManutField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ocorrencia
        {
            get
            {
                return this.ocorrenciaField;
            }
            set
            {
                this.ocorrenciaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Referencia
        {
            get
            {
                return this.referenciaField;
            }
            set
            {
                this.referenciaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ServicoContratado
        {
            get
            {
                return this.servicoContratadoField;
            }
            set
            {
                this.servicoContratadoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FilialDesignada
        {
            get
            {
                return this.filialDesignadaField;
            }
            set
            {
                this.filialDesignadaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Observacao
        {
            get
            {
                return this.observacaoField;
            }
            set
            {
                this.observacaoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodigoAcesso
        {
            get
            {
                return this.codigoAcessoField;
            }
            set
            {
                this.codigoAcessoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KitSinalizacao", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Kit_DT[] KitSinalizacao
        {
            get
            {
                return this.kitSinalizacaoField;
            }
            set
            {
                this.kitSinalizacaoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:visanet:legancy:gtec:opl")]
    public partial class Cobranca_DT
    {

        private string chamadoGTECField = "";

        private string contatoECField = "";

        private string descricaoField = "";

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ChamadoGTEC
        {
            get
            {
                return this.chamadoGTECField;
            }
            set
            {
                this.chamadoGTECField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ContatoEC
        {
            get
            {
                return this.contatoECField;
            }
            set
            {
                this.contatoECField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Descricao
        {
            get
            {
                return this.descricaoField;
            }
            set
            {
                this.descricaoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:visanet:legancy:gtec:opl")]
    public partial class Equipamento_DT
    {

        private string tipoField = "";

        private string modeloField = "";

        private string numeroLogicoField = "";

        private string sAMField = "";

        private bool novoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Modelo
        {
            get
            {
                return this.modeloField;
            }
            set
            {
                this.modeloField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NumeroLogico
        {
            get
            {
                return this.numeroLogicoField;
            }
            set
            {
                this.numeroLogicoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SAM
        {
            get
            {
                return this.sAMField;
            }
            set
            {
                this.sAMField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool Novo
        {
            get
            {
                return this.novoField;
            }
            set
            {
                this.novoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    public delegate void GtecService_MICompletedEventHandler(object sender, GtecService_MICompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GtecService_MICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GtecService_MICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public Return_DT Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((Return_DT)(this.results[0]));
            }
        }
    }
}

/*
	Eliminar:
	- GtecService_MI2
	- msgGtec_DT2
	- Cliente_DT2
*/
