//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Senac.Fecomercio.BLL.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagens() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Senac.Fecomercio.BLL.Resources.Mensagens", typeof(Mensagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0:dd/MM/yyyy HH:mm:ss} PROCESSAMENTO FINALIZADO COM SUCESSO
        ///Quantidade de registros processados com sucesso: {1}
        ///Quantidade de registros rejeitados: {2}.
        /// </summary>
        internal static string MSG_ResumoFinalProcesso {
            get {
                return ResourceManager.GetString("MSG_ResumoFinalProcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha na execução do processo {0}, pasta {1} não existe ou está inacessível.
        /// </summary>
        internal static string MSG002_PastaNaoExiste {
            get {
                return ResourceManager.GetString("MSG002_PastaNaoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Linha: {0};{1};Campo com erro: {2};Erro de validação: {3}.
        /// </summary>
        internal static string MSG005_ErroValidacao {
            get {
                return ResourceManager.GetString("MSG005_ErroValidacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Linha: {0};{1};Chave do registro em duplicidade no arquivo.
        /// </summary>
        internal static string MSG006_LinhaRepedida {
            get {
                return ResourceManager.GetString("MSG006_LinhaRepedida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro de validação: &lt;br&gt; Linha: {0} &lt;br&gt; Campo com erro: {1}&lt;br&gt; Erro identificado: {2}&lt;br&gt;.
        /// </summary>
        internal static string MSG009_FalhaValidacaoTransmisao {
            get {
                return ResourceManager.GetString("MSG009_FalhaValidacaoTransmisao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Linha: {0};{1};Inclusão não permitida quando registro já existe na base.
        /// </summary>
        internal static string MSG011_Inclusao_Existe {
            get {
                return ResourceManager.GetString("MSG011_Inclusao_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Linha: {0};{1};Exclusão não permitida quando registro não existe na base.
        /// </summary>
        internal static string MSG012_Exclusao_Nao_Existe {
            get {
                return ResourceManager.GetString("MSG012_Exclusao_Nao_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Linha: {0};{1};Exclusão não permitida pois foi encontrado mais que um registro na base.
        /// </summary>
        internal static string MSG013_Exclusao_Mais_Que_Um_Registro_Encontrado {
            get {
                return ResourceManager.GetString("MSG013_Exclusao_Mais_Que_Um_Registro_Encontrado", resourceCulture);
            }
        }
    }
}
