//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Senac.Fecomercio.ControlaWebServices.svcOsbAbrirEvento {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/comum/v1")]
    public partial class Fault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string descricaoField;
        
        private Tipo tipoField;
        
        private string sistemaOrigemField;
        
        private string servicoOrigemField;
        
        private FaultDetail detalheField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
                this.RaisePropertyChanged("descricao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Tipo tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string sistemaOrigem {
            get {
                return this.sistemaOrigemField;
            }
            set {
                this.sistemaOrigemField = value;
                this.RaisePropertyChanged("sistemaOrigem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string servicoOrigem {
            get {
                return this.servicoOrigemField;
            }
            set {
                this.servicoOrigemField = value;
                this.RaisePropertyChanged("servicoOrigem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public FaultDetail detalhe {
            get {
                return this.detalheField;
            }
            set {
                this.detalheField = value;
                this.RaisePropertyChanged("detalhe");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/comum/v1")]
    public enum Tipo {
        
        /// <remarks/>
        NEGOCIO,
        
        /// <remarks/>
        TECNICO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/comum/v1")]
    public partial class FaultDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.cielo.com.br/apoionegocio/tecnologiainformacao/evento/v21/abrireve" +
        "nto")]
    public partial class AbrirEventoRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoEventoField;
        
        private long codigoClienteField;
        
        private string descricaoLinha1Field;
        
        private string descricaoLinha2Field;
        
        private string descricaoLinha3Field;
        
        private string descricaoLinha4Field;
        
        private string descricaoLinha5Field;
        
        private string descricaoLinha6Field;
        
        private string codigoDependenciaField;
        
        private string nomeCanalSolicitanteField;
        
        private string nomeUsuarioOperadorField;
        
        private string codigoStatusEventoField;
        
        private bool indicadorConfirmacaoField;
        
        private bool indicadorConfirmacaoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int codigoEvento {
            get {
                return this.codigoEventoField;
            }
            set {
                this.codigoEventoField = value;
                this.RaisePropertyChanged("codigoEvento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long codigoCliente {
            get {
                return this.codigoClienteField;
            }
            set {
                this.codigoClienteField = value;
                this.RaisePropertyChanged("codigoCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string descricaoLinha1 {
            get {
                return this.descricaoLinha1Field;
            }
            set {
                this.descricaoLinha1Field = value;
                this.RaisePropertyChanged("descricaoLinha1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string descricaoLinha2 {
            get {
                return this.descricaoLinha2Field;
            }
            set {
                this.descricaoLinha2Field = value;
                this.RaisePropertyChanged("descricaoLinha2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string descricaoLinha3 {
            get {
                return this.descricaoLinha3Field;
            }
            set {
                this.descricaoLinha3Field = value;
                this.RaisePropertyChanged("descricaoLinha3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string descricaoLinha4 {
            get {
                return this.descricaoLinha4Field;
            }
            set {
                this.descricaoLinha4Field = value;
                this.RaisePropertyChanged("descricaoLinha4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string descricaoLinha5 {
            get {
                return this.descricaoLinha5Field;
            }
            set {
                this.descricaoLinha5Field = value;
                this.RaisePropertyChanged("descricaoLinha5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string descricaoLinha6 {
            get {
                return this.descricaoLinha6Field;
            }
            set {
                this.descricaoLinha6Field = value;
                this.RaisePropertyChanged("descricaoLinha6");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=8)]
        public string codigoDependencia {
            get {
                return this.codigoDependenciaField;
            }
            set {
                this.codigoDependenciaField = value;
                this.RaisePropertyChanged("codigoDependencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string nomeCanalSolicitante {
            get {
                return this.nomeCanalSolicitanteField;
            }
            set {
                this.nomeCanalSolicitanteField = value;
                this.RaisePropertyChanged("nomeCanalSolicitante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string nomeUsuarioOperador {
            get {
                return this.nomeUsuarioOperadorField;
            }
            set {
                this.nomeUsuarioOperadorField = value;
                this.RaisePropertyChanged("nomeUsuarioOperador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string codigoStatusEvento {
            get {
                return this.codigoStatusEventoField;
            }
            set {
                this.codigoStatusEventoField = value;
                this.RaisePropertyChanged("codigoStatusEvento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool indicadorConfirmacao {
            get {
                return this.indicadorConfirmacaoField;
            }
            set {
                this.indicadorConfirmacaoField = value;
                this.RaisePropertyChanged("indicadorConfirmacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool indicadorConfirmacaoSpecified {
            get {
                return this.indicadorConfirmacaoFieldSpecified;
            }
            set {
                this.indicadorConfirmacaoFieldSpecified = value;
                this.RaisePropertyChanged("indicadorConfirmacaoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.cielo.com.br/apoionegocio/tecnologiainformacao/evento/v21/abrireve" +
        "nto", ConfigurationName="svcOsbAbrirEvento.Evento_abrirEventoServicePortType")]
    public interface Evento_abrirEventoServicePortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.cielo.com.br/apoionegocio/tecnologiainformacao/evento/v21/abrireve" +
            "nto", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Senac.Fecomercio.ControlaWebServices.svcOsbAbrirEvento.Fault), Action="http://service.cielo.com.br/apoionegocio/tecnologiainformacao/evento/v21/abrireve" +
            "nto", Name="fault", Namespace="http://canonico.cielo.com.br/comum/v1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Senac.Fecomercio.ControlaWebServices.svcOsbAbrirEvento.abrirEventoResponse abrirEvento(Senac.Fecomercio.ControlaWebServices.svcOsbAbrirEvento.abrirEventoRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.cielo.com.br/apoionegocio/tecnologiainformacao/evento/v21/abrireve" +
            "nto", ReplyAction="*")]
        System.Threading.Tasks.Task<Senac.Fecomercio.ControlaWebServices.svcOsbAbrirEvento.abrirEventoResponse> abrirEventoAsync(Senac.Fecomercio.ControlaWebServices.svcOsbAbrirEvento.abrirEventoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/governancasoa/comum/v1")]
    public partial class CieloSoapHeaderType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object itemField;
        
        private string recursoField;
        
        private string realmField;
        
        private IdentificacaoRequestType identificacaoRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("token", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("usuario", typeof(UsuarioType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string recurso {
            get {
                return this.recursoField;
            }
            set {
                this.recursoField = value;
                this.RaisePropertyChanged("recurso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string realm {
            get {
                return this.realmField;
            }
            set {
                this.realmField = value;
                this.RaisePropertyChanged("realm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public IdentificacaoRequestType identificacaoRequest {
            get {
                return this.identificacaoRequestField;
            }
            set {
                this.identificacaoRequestField = value;
                this.RaisePropertyChanged("identificacaoRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/governancasoa/comum/v1")]
    public partial class UsuarioType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string senhaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
                this.RaisePropertyChanged("senha");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://canonico.cielo.com.br/governancasoa/comum/v1")]
    public partial class IdentificacaoRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nomeSistemaField;
        
        private string nomeTipoChamadaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nomeSistema {
            get {
                return this.nomeSistemaField;
            }
            set {
                this.nomeSistemaField = value;
                this.RaisePropertyChanged("nomeSistema");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nomeTipoChamada {
            get {
                return this.nomeTipoChamadaField;
            }
            set {
                this.nomeTipoChamadaField = value;
                this.RaisePropertyChanged("nomeTipoChamada");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class abrirEventoRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://canonico.cielo.com.br/governancasoa/comum/v1")]
        public Senac.Fecomercio.ControlaWebServices.svcOsbAbrirEvento.CieloSoapHeaderType cieloSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="abrirEventoRequest", Namespace="http://service.cielo.com.br/apoionegocio/tecnologiainformacao/evento/v21/abrireve" +
            "nto", Order=0)]
        public Senac.Fecomercio.ControlaWebServices.svcOsbAbrirEvento.AbrirEventoRequestType abrirEventoRequest1;
        
        public abrirEventoRequest() {
        }
        
        public abrirEventoRequest(Senac.Fecomercio.ControlaWebServices.svcOsbAbrirEvento.CieloSoapHeaderType cieloSoapHeader, Senac.Fecomercio.ControlaWebServices.svcOsbAbrirEvento.AbrirEventoRequestType abrirEventoRequest1) {
            this.cieloSoapHeader = cieloSoapHeader;
            this.abrirEventoRequest1 = abrirEventoRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="abrirEventoResponse", WrapperNamespace="http://service.cielo.com.br/apoionegocio/tecnologiainformacao/evento/v21/abrireve" +
        "nto", IsWrapped=true)]
    public partial class abrirEventoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/apoionegocio/tecnologiainformacao/evento/v21/abrireve" +
            "nto", Order=0)]
        public int codigoErro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cielo.com.br/apoionegocio/tecnologiainformacao/evento/v21/abrireve" +
            "nto", Order=1)]
        public long numeroRegistroEvento;
        
        public abrirEventoResponse() {
        }
        
        public abrirEventoResponse(int codigoErro, long numeroRegistroEvento) {
            this.codigoErro = codigoErro;
            this.numeroRegistroEvento = numeroRegistroEvento;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Evento_abrirEventoServicePortTypeChannel : Senac.Fecomercio.ControlaWebServices.svcOsbAbrirEvento.Evento_abrirEventoServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Evento_abrirEventoServicePortTypeClient : System.ServiceModel.ClientBase<Senac.Fecomercio.ControlaWebServices.svcOsbAbrirEvento.Evento_abrirEventoServicePortType>, Senac.Fecomercio.ControlaWebServices.svcOsbAbrirEvento.Evento_abrirEventoServicePortType {
        
        public Evento_abrirEventoServicePortTypeClient() {
        }
        
        public Evento_abrirEventoServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Evento_abrirEventoServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Evento_abrirEventoServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Evento_abrirEventoServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Senac.Fecomercio.ControlaWebServices.svcOsbAbrirEvento.abrirEventoResponse Senac.Fecomercio.ControlaWebServices.svcOsbAbrirEvento.Evento_abrirEventoServicePortType.abrirEvento(Senac.Fecomercio.ControlaWebServices.svcOsbAbrirEvento.abrirEventoRequest request) {
            return base.Channel.abrirEvento(request);
        }
        
        public int abrirEvento(Senac.Fecomercio.ControlaWebServices.svcOsbAbrirEvento.CieloSoapHeaderType cieloSoapHeader, Senac.Fecomercio.ControlaWebServices.svcOsbAbrirEvento.AbrirEventoRequestType abrirEventoRequest1, out long numeroRegistroEvento) {
            Senac.Fecomercio.ControlaWebServices.svcOsbAbrirEvento.abrirEventoRequest inValue = new Senac.Fecomercio.ControlaWebServices.svcOsbAbrirEvento.abrirEventoRequest();
            inValue.cieloSoapHeader = cieloSoapHeader;
            inValue.abrirEventoRequest1 = abrirEventoRequest1;
            Senac.Fecomercio.ControlaWebServices.svcOsbAbrirEvento.abrirEventoResponse retVal = ((Senac.Fecomercio.ControlaWebServices.svcOsbAbrirEvento.Evento_abrirEventoServicePortType)(this)).abrirEvento(inValue);
            numeroRegistroEvento = retVal.numeroRegistroEvento;
            return retVal.codigoErro;
        }
        
        public System.Threading.Tasks.Task<Senac.Fecomercio.ControlaWebServices.svcOsbAbrirEvento.abrirEventoResponse> abrirEventoAsync(Senac.Fecomercio.ControlaWebServices.svcOsbAbrirEvento.abrirEventoRequest request) {
            return base.Channel.abrirEventoAsync(request);
        }
    }
}
