//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Senac.Fecomercio.ControlaWebServices.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://cbmphorhpi1:52100/XISOAPAdapter/MessageServlet?senderParty=&senderService=" +
            "Gtec_HBS&receiverParty=&receiverService=&interface=VendaTerminal_out_SI&interfac" +
            "eNamespace=urn%3Acielo%3Agtec%3Apax%3AVendaTerminal")]
        public string Cielo_Gtec_ControlaWebServices_svcPAXVendaTerminal_v2_Gtec_HBS_VendaTerminal_out_SI {
            get {
                return ((string)(this["Cielo_Gtec_ControlaWebServices_svcPAXVendaTerminal_v2_Gtec_HBS_VendaTerminal_out_" +
                    "SI"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://vwhsappo01.ccorp.local:52100/XISOAPAdapter/MessageServlet?senderParty=&sen" +
            "derService=Gtec&receiverParty=&receiverService=&interface=GtecService_MI&interfa" +
            "ceNamespace=urn%3Avisanet%3Alegancy%3Agtec%3Aopl")]
        public string Cielo_Gtec_ControlaWebServices_svcSAP_PO_GtecService_MIService {
            get {
                return ((string)(this["Cielo_Gtec_ControlaWebServices_svcSAP_PO_GtecService_MIService"]));
            }
        }
    }
}
