//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Senac.Fecomercio.ControlaWebServices.WS_SoftwareExpress {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CheckoutMovel_Habilitacao_sync_out_SIBinding", Namespace="urn:cielo:gtec:software_house")]
    public partial class Gtec_BS_CheckoutMovel_Habilitacao_sync_out_SI : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CheckoutMovel_Habilitacao_sync_out_SIOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Gtec_BS_CheckoutMovel_Habilitacao_sync_out_SI() {
            this.Url = "http://cbmphordpi1.cbmp.corp:51100/XISOAPAdapter/MessageServlet?senderParty=&send" +
                "erService=Gtec_BS&receiverParty=&receiverService=&interface=CheckoutMovel_Habili" +
                "tacao_sync_out_SI&interfaceNamespace=urn%3Acielo%3Agtec%3Asoftware_house";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CheckoutMovel_Habilitacao_sync_out_SICompletedEventHandler CheckoutMovel_Habilitacao_sync_out_SICompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("habilitaTerminalResponse", Namespace="http://ws.configuracao.agt.softwareexpress.com.br/")]
        public habilitaTerminalResponse CheckoutMovel_Habilitacao_sync_out_SI([System.Xml.Serialization.XmlElementAttribute(Namespace="http://ws.configuracao.agt.softwareexpress.com.br/")] habilitaTerminal habilitaTerminal) {
            object[] results = this.Invoke("CheckoutMovel_Habilitacao_sync_out_SI", new object[] {
                        habilitaTerminal});
            return ((habilitaTerminalResponse)(results[0]));
        }
        
        /// <remarks/>
        public void CheckoutMovel_Habilitacao_sync_out_SIAsync(habilitaTerminal habilitaTerminal) {
            this.CheckoutMovel_Habilitacao_sync_out_SIAsync(habilitaTerminal, null);
        }
        
        /// <remarks/>
        public void CheckoutMovel_Habilitacao_sync_out_SIAsync(habilitaTerminal habilitaTerminal, object userState) {
            if ((this.CheckoutMovel_Habilitacao_sync_out_SIOperationCompleted == null)) {
                this.CheckoutMovel_Habilitacao_sync_out_SIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckoutMovel_Habilitacao_sync_out_SIOperationCompleted);
            }
            this.InvokeAsync("CheckoutMovel_Habilitacao_sync_out_SI", new object[] {
                        habilitaTerminal}, this.CheckoutMovel_Habilitacao_sync_out_SIOperationCompleted, userState);
        }
        
        private void OnCheckoutMovel_Habilitacao_sync_out_SIOperationCompleted(object arg) {
            if ((this.CheckoutMovel_Habilitacao_sync_out_SICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckoutMovel_Habilitacao_sync_out_SICompleted(this, new CheckoutMovel_Habilitacao_sync_out_SICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.configuracao.agt.softwareexpress.com.br/")]
    public partial class habilitaTerminal {
        
        private habilitaTerminalReq habilitaTerminalReqField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public habilitaTerminalReq habilitaTerminalReq {
            get {
                return this.habilitaTerminalReqField;
            }
            set {
                this.habilitaTerminalReqField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.configuracao.agt.softwareexpress.com.br/")]
    public partial class habilitaTerminalReq {
        
        private string chaveAcessoField;
        
        private int codigoRedeCapturaField;
        
        private string operacaoField;
        
        private terminalWS[] terminalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string chaveAcesso {
            get {
                return this.chaveAcessoField;
            }
            set {
                this.chaveAcessoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoRedeCaptura {
            get {
                return this.codigoRedeCapturaField;
            }
            set {
                this.codigoRedeCapturaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string operacao {
            get {
                return this.operacaoField;
            }
            set {
                this.operacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("terminal", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public terminalWS[] terminal {
            get {
                return this.terminalField;
            }
            set {
                this.terminalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.configuracao.agt.softwareexpress.com.br/")]
    public partial class terminalWS {
        
        private long chamadoGTECField;
        
        private string cnpjField;
        
        private string filialDesignadaField;
        
        private string identificacaoExtraField;
        
        private string identificacaoTerminalField;
        
        private string modeloEquipamentoField;
        
        private string motivoEventoField;
        
        private string novoRemanejadoField;
        
        private int numeroLoteField;
        
        private string observacaoField;
        
        private string prestadorServicoField;
        
        private int segChamadoGTECField;
        
        private string servicoContratadoField;
        
        private string tipoEquipamentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long chamadoGTEC {
            get {
                return this.chamadoGTECField;
            }
            set {
                this.chamadoGTECField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cnpj {
            get {
                return this.cnpjField;
            }
            set {
                this.cnpjField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string filialDesignada {
            get {
                return this.filialDesignadaField;
            }
            set {
                this.filialDesignadaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string identificacaoExtra {
            get {
                return this.identificacaoExtraField;
            }
            set {
                this.identificacaoExtraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string identificacaoTerminal {
            get {
                return this.identificacaoTerminalField;
            }
            set {
                this.identificacaoTerminalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string modeloEquipamento {
            get {
                return this.modeloEquipamentoField;
            }
            set {
                this.modeloEquipamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string motivoEvento {
            get {
                return this.motivoEventoField;
            }
            set {
                this.motivoEventoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string novoRemanejado {
            get {
                return this.novoRemanejadoField;
            }
            set {
                this.novoRemanejadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int numeroLote {
            get {
                return this.numeroLoteField;
            }
            set {
                this.numeroLoteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string observacao {
            get {
                return this.observacaoField;
            }
            set {
                this.observacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string prestadorServico {
            get {
                return this.prestadorServicoField;
            }
            set {
                this.prestadorServicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int segChamadoGTEC {
            get {
                return this.segChamadoGTECField;
            }
            set {
                this.segChamadoGTECField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string servicoContratado {
            get {
                return this.servicoContratadoField;
            }
            set {
                this.servicoContratadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string tipoEquipamento {
            get {
                return this.tipoEquipamentoField;
            }
            set {
                this.tipoEquipamentoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.configuracao.agt.softwareexpress.com.br/")]
    public partial class terminalWSResp {
        
        private long chamadoGTECField;
        
        private bool chamadoGTECFieldSpecified;
        
        private string cnpjField;
        
        private string erroField;
        
        private string identificacaoExtraField;
        
        private string identificacaoTerminalField;
        
        private int numeroLoteField;
        
        private bool numeroLoteFieldSpecified;
        
        private int retornoField;
        
        private bool retornoFieldSpecified;
        
        private int segChamadoGTECField;
        
        private bool segChamadoGTECFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long chamadoGTEC {
            get {
                return this.chamadoGTECField;
            }
            set {
                this.chamadoGTECField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool chamadoGTECSpecified {
            get {
                return this.chamadoGTECFieldSpecified;
            }
            set {
                this.chamadoGTECFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cnpj {
            get {
                return this.cnpjField;
            }
            set {
                this.cnpjField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string erro {
            get {
                return this.erroField;
            }
            set {
                this.erroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string identificacaoExtra {
            get {
                return this.identificacaoExtraField;
            }
            set {
                this.identificacaoExtraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string identificacaoTerminal {
            get {
                return this.identificacaoTerminalField;
            }
            set {
                this.identificacaoTerminalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int numeroLote {
            get {
                return this.numeroLoteField;
            }
            set {
                this.numeroLoteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroLoteSpecified {
            get {
                return this.numeroLoteFieldSpecified;
            }
            set {
                this.numeroLoteFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int retorno {
            get {
                return this.retornoField;
            }
            set {
                this.retornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool retornoSpecified {
            get {
                return this.retornoFieldSpecified;
            }
            set {
                this.retornoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int segChamadoGTEC {
            get {
                return this.segChamadoGTECField;
            }
            set {
                this.segChamadoGTECField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool segChamadoGTECSpecified {
            get {
                return this.segChamadoGTECFieldSpecified;
            }
            set {
                this.segChamadoGTECFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.configuracao.agt.softwareexpress.com.br/")]
    public partial class habilitaTerminalResp {
        
        private string chaveAcessoField;
        
        private int codigoRedeCapturaField;
        
        private bool codigoRedeCapturaFieldSpecified;
        
        private string operacaoField;
        
        private int resultadoChamadaField;
        
        private bool resultadoChamadaFieldSpecified;
        
        private string resultadoDescricaoField;
        
        private terminalWSResp[] terminaisField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string chaveAcesso {
            get {
                return this.chaveAcessoField;
            }
            set {
                this.chaveAcessoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoRedeCaptura {
            get {
                return this.codigoRedeCapturaField;
            }
            set {
                this.codigoRedeCapturaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoRedeCapturaSpecified {
            get {
                return this.codigoRedeCapturaFieldSpecified;
            }
            set {
                this.codigoRedeCapturaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string operacao {
            get {
                return this.operacaoField;
            }
            set {
                this.operacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int resultadoChamada {
            get {
                return this.resultadoChamadaField;
            }
            set {
                this.resultadoChamadaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resultadoChamadaSpecified {
            get {
                return this.resultadoChamadaFieldSpecified;
            }
            set {
                this.resultadoChamadaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string resultadoDescricao {
            get {
                return this.resultadoDescricaoField;
            }
            set {
                this.resultadoDescricaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("terminais", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public terminalWSResp[] terminais {
            get {
                return this.terminaisField;
            }
            set {
                this.terminaisField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.configuracao.agt.softwareexpress.com.br/")]
    public partial class habilitaTerminalResponse {
        
        private habilitaTerminalResp responseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public habilitaTerminalResp response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void CheckoutMovel_Habilitacao_sync_out_SICompletedEventHandler(object sender, CheckoutMovel_Habilitacao_sync_out_SICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckoutMovel_Habilitacao_sync_out_SICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckoutMovel_Habilitacao_sync_out_SICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public habilitaTerminalResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((habilitaTerminalResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591